// Script:    TesteMesaComContador.script
// Autor:     Gustavo Contreiras, João Victor Galindo, Thiago Gioso Fernandes
// Data:      05/mai/2018
// Propósito: Testar o módulo baralho do jogo de truco
//

== Inicializar valores validos de indice do vetor maos
=declararparm   mao0	int 0
=declararparm   mao1	int 1
=declararparm   mao2	int 2
=declararparm   mao3	int 3
=declararparm   mao4	int 4
=declararparm   mao5	int 5

== Iniciar contagem
=inicializarcontadores  ""
=lercontadores          "..\\scripts\\Mesa"
=iniciarcontagem

== Verificar quantidade de contadores com zero
=verificarcontagens 10

== Verificar quantidade de contadores contados
=contagemcontador   "MES_CriarListaDeListas - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_CriarListaDeListas - Depois de atribuir valor NaoNULL e antes de sair"  0
=contagemcontador   "MES_CriarMao - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_CriarMao - Depois de atribuir valor NaoNULL e antes de sair"  0
=contagemcontador   "MES_CriarLixo - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_CriarLixo - Depois de atribuir valor NaoNULL e antes de sair"  0
=contagemcontador   "MES_CriarMesa - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_CriarMesa - Depois de atribuir valor NaoNULL e antes de sair"  0
=contagemcontador   "MES_DistribuirMaos - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_DistribuirMaos - Depois de sair do switch e antes de retornar"  0

== Verificar falhas (contador com zero eh uma falha)
=AceitaFalhasAcumuladas 10

== TESTE
=resetteste

== Criar lista de listas
=criarlistadelistas

== Verificar quantidade de contadores com zero
=verificarcontagens 8

== Verificar quantidade de contadores contados
=contagemcontador   "MES_CriarListaDeListas - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_CriarListaDeListas - Depois de atribuir valor NaoNULL e antes de sair"  1
=contagemcontador   "MES_CriarMao - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_CriarMao - Depois de atribuir valor NaoNULL e antes de sair"  0
=contagemcontador   "MES_CriarLixo - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_CriarLixo - Depois de atribuir valor NaoNULL e antes de sair"  0
=contagemcontador   "MES_CriarMesa - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_CriarMesa - Depois de atribuir valor NaoNULL e antes de sair"  0
=contagemcontador   "MES_DistribuirMaos - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_DistribuirMaos - Depois de sair do switch e antes de retornar"  0

== Verificar falhas (contador com zero eh uma falha)
=AceitaFalhasAcumuladas 8

== Criar todas mãos
=criarmao mao0
=criarmao mao1
=criarmao mao2
=criarmao mao3
=criarmao mao4
=criarmao mao5

== Verificar quantidade de contadores com zero
=verificarcontagens 6

== Verificar quantidade de contadores contados
=contagemcontador   "MES_CriarListaDeListas - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_CriarListaDeListas - Depois de atribuir valor NaoNULL e antes de sair"  1
=contagemcontador   "MES_CriarMao - Depois de entrar e declarar variaveis"  6
=contagemcontador   "MES_CriarMao - Depois de atribuir valor NaoNULL e antes de sair"  6
=contagemcontador   "MES_CriarLixo - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_CriarLixo - Depois de atribuir valor NaoNULL e antes de sair"  0
=contagemcontador   "MES_CriarMesa - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_CriarMesa - Depois de atribuir valor NaoNULL e antes de sair"  0
=contagemcontador   "MES_DistribuirMaos - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_DistribuirMaos - Depois de sair do switch e antes de retornar"  0

== Verificar falhas (contador com zero eh uma falha)
=AceitaFalhasAcumuladas 6

== Criar lixo
=criarlixo

== Verificar quantidade de contadores com zero
=verificarcontagens 4

== Verificar quantidade de contadores contados
=contagemcontador   "MES_CriarListaDeListas - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_CriarListaDeListas - Depois de atribuir valor NaoNULL e antes de sair"  1
=contagemcontador   "MES_CriarMao - Depois de entrar e declarar variaveis"  6
=contagemcontador   "MES_CriarMao - Depois de atribuir valor NaoNULL e antes de sair"  6
=contagemcontador   "MES_CriarLixo - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_CriarLixo - Depois de atribuir valor NaoNULL e antes de sair"  1
=contagemcontador   "MES_CriarMesa - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_CriarMesa - Depois de atribuir valor NaoNULL e antes de sair"  0
=contagemcontador   "MES_DistribuirMaos - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_DistribuirMaos - Depois de sair do switch e antes de retornar"  0

== Verificar falhas (contador com zero eh uma falha)
=AceitaFalhasAcumuladas 4

== Criar mesa
=criarmesa

== Verificar quantidade de contadores com zero
=verificarcontagens 2

== Verificar quantidade de contadores contados
=contagemcontador   "MES_CriarListaDeListas - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_CriarListaDeListas - Depois de atribuir valor NaoNULL e antes de sair"  1
=contagemcontador   "MES_CriarMao - Depois de entrar e declarar variaveis"  6
=contagemcontador   "MES_CriarMao - Depois de atribuir valor NaoNULL e antes de sair"  6
=contagemcontador   "MES_CriarLixo - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_CriarLixo - Depois de atribuir valor NaoNULL e antes de sair"  1
=contagemcontador   "MES_CriarMesa - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_CriarMesa - Depois de atribuir valor NaoNULL e antes de sair"  1
=contagemcontador   "MES_DistribuirMaos - Depois de entrar e declarar variaveis"  0
=contagemcontador   "MES_DistribuirMaos - Depois de sair do switch e antes de retornar"  0

== Verificar falhas (contador com zero eh uma falha)
=AceitaFalhasAcumuladas 2

== Distribuir maos
=distribuirmaos 6

== Verificar quantidade de contadores com zero
=verificarcontagens 0

== Verificar quantidade de contadores contados
=contagemcontador   "MES_CriarListaDeListas - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_CriarListaDeListas - Depois de atribuir valor NaoNULL e antes de sair"  1
=contagemcontador   "MES_CriarMao - Depois de entrar e declarar variaveis"  6
=contagemcontador   "MES_CriarMao - Depois de atribuir valor NaoNULL e antes de sair"  6
=contagemcontador   "MES_CriarLixo - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_CriarLixo - Depois de atribuir valor NaoNULL e antes de sair"  1
=contagemcontador   "MES_CriarMesa - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_CriarMesa - Depois de atribuir valor NaoNULL e antes de sair"  1
=contagemcontador   "MES_DistribuirMaos - Depois de entrar e declarar variaveis"  1
=contagemcontador   "MES_DistribuirMaos - Depois de sair do switch e antes de retornar"  1

== Terminar controlar contadores
=pararcontagem
=verificarcontagens 0

== Terminar contagem
=terminarcontadores

// fim