# Jogo de Truco com Debug usando os módulos interface, mesa, baralho e lista e a biblioteca contendo o arcabouço

[Diretorios]

Nome        =  JogoDeTrucoDebug
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas

[Modulos]
Lista
Baralho
Mesa
Interface /D_DEBUG


[BuildInicio]
/OUT:..\produto\JogoDeTrucoDebug.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
