# Teste do módulo lista usando a biblioteca contendo o arcabouço

[Diretorios]

Nome        =  TesteListaProd
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas

[Modulos]
Lista
TestLIS

[BuildInicio]
/OUT:..\produto\TesteListaProd.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
